export type Scope =
  | 'profile'
  | 'read:faq'
  | 'write:faq'
  | 'admin:faq'
  | 'read:announcement'
  | 'write:announcement'
  | 'admin:announcement'
  | 'read:inquiry'
  | 'write:inquiry'
  | 'admin:inquiry'
  | 'read:workspace'
  | 'admin:workspace'
